/*
 * OpenScope 2C53T - Multi-size Font System
 *
 * Variable-width bitmap fonts rendered from TTF sources.
 * Each font contains: glyph bitmaps (1-bit/pixel), per-glyph widths,
 * advance widths, and a charmap for ASCII lookup.
 *
 * Generated by: scripts/generate_font.py
 */

#ifndef FONT_H
#define FONT_H

#include <stdint.h>

/* Font descriptor */
typedef struct {
    uint8_t         height;      /* Glyph height in pixels (constant for all glyphs) */
    uint8_t         first_char;  /* First ASCII code in charmap */
    uint8_t         last_char;   /* Last ASCII code in charmap */
    uint8_t         num_glyphs;  /* Total number of glyphs */
    const uint8_t  *data;        /* Packed bitmap data (1 bit/pixel, MSB first) */
    const uint16_t *offsets;     /* Byte offset into data[] for each glyph */
    const uint8_t  *widths;      /* Pixel width of each glyph */
    const uint8_t  *advances;    /* Horizontal advance (width + spacing) per glyph */
    const uint8_t  *charmap;     /* Maps (ascii - first_char) -> glyph index */
} font_t;

/* ========================================================================
 * Available fonts (defined in generated .c files)
 * ======================================================================== */

extern const font_t font_small;    /* ~12px - status bars, labels */
extern const font_t font_medium;   /* ~16px - general UI text */
extern const font_t font_large;    /* ~24px - channel labels, measurements */
extern const font_t font_xlarge;   /* ~48px - DMM main reading */

/* ========================================================================
 * Rendering functions
 * ======================================================================== */

/*
 * Draw a single character. Returns advance width (pixels to next char).
 * If bg == fg, draws with transparent background (only foreground pixels).
 */
uint8_t font_draw_char(uint16_t x, uint16_t y, char c,
                       uint16_t fg, uint16_t bg, const font_t *font);

/*
 * Draw a string. Returns total width in pixels.
 * If bg == fg, draws with transparent background.
 */
uint16_t font_draw_string(uint16_t x, uint16_t y, const char *str,
                          uint16_t fg, uint16_t bg, const font_t *font);

/*
 * Measure string width without drawing (for centering, alignment).
 */
uint16_t font_string_width(const char *str, const font_t *font);

/*
 * Draw a string right-aligned to the given x coordinate.
 * Useful for numeric displays where digits shouldn't jump around.
 */
uint16_t font_draw_string_right(uint16_t x_right, uint16_t y, const char *str,
                                uint16_t fg, uint16_t bg, const font_t *font);

/*
 * Draw a string centered horizontally at the given x coordinate.
 */
uint16_t font_draw_string_center(uint16_t x_center, uint16_t y, const char *str,
                                 uint16_t fg, uint16_t bg, const font_t *font);

#endif /* FONT_H */
