#!/usr/bin/env python3
"""Generate firmware/tests/fixtures/mask_pf_records.h for tests/test_mask_pf.c.

Source: the v0.4.0 release regression capture on unit #1
(reverse_engineering/captures/exp54/exp22_trigger_block_v0.4.0_frames.npz,
2026-09-30): committed CH1 records, range 5, trigger level 0 (reg 0x08 code
128 -> record crossing 100), rising, JDS sine into CH1.

Groups and what the test uses them for:
  hpos40    6  teach set (HPOS x=40 block)
  hpos160   6  held-out, same signal + timebase, captured minutes later
  hpos280   6  held-out, ditto
  sine10    5  held-out, the NORMAL 0x10 block (earliest in the run)
  single    3  held-out, SINGLE one-shot block
  sine11    5  NEGATIVE: same drive, timebase 0x11 (half the rate)
  sq4hz     2  REFUSAL: 4 Hz square at 0x10, no crossing of 100 near 512

Every record carries the generation number it was committed with, so a
failing assertion can be traced back to the capture log.
"""
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "reverse_engineering/captures/exp54/exp22_trigger_block_v0.4.0_frames.npz"
OUT = ROOT / "firmware/tests/fixtures/mask_pf_records.h"

GROUPS = [
    ("hpos40",  "TRIG_HPOS_x=40",              None),
    ("hpos160", "TRIG_HPOS_x=160",             None),
    ("hpos280", "TRIG_HPOS_x=280",             None),
    ("sine10",  "TRIG_NORMAL_0x10_sine",       None),
    ("single",  "TRIG_SINGLE_one-shot",        None),
    ("sine11",  "TRIG_NORMAL_0x11_sine",       None),
    ("sq4hz",   "TRIG_NORMAL_square_4Hz_0x10", 2),
]


def main():
    z = np.load(SRC)
    lines = [
        "/* GENERATED by scripts/gen_mask_pf_fixture.py -- do not edit.",
        f" * Source: {SRC.relative_to(ROOT)}",
        " * Committed CH1 records from unit #1, v0.4.0 regression run 2026-09-30,",
        " * range 5, level 0 (record crossing 100), rising. See the script for",
        " * what each group is for. */",
        "#include <stdint.h>",
        "typedef struct { const char *group; int gen; uint8_t rec[1024]; } mask_fixture_t;",
        "static const mask_fixture_t MASK_FIXTURES[] = {",
    ]
    for tag, key, limit in GROUPS:
        recs = z[key + "__ch1"]
        gens = z[key + "__gen"]
        n = len(recs) if limit is None else min(limit, len(recs))
        for r, g in zip(recs[:n], gens[:n]):
            assert r.shape == (1024,) and r.dtype == np.uint8
            lines.append(f'  {{ "{tag}", {int(g)}, {{{",".join(str(int(v)) for v in r)}}} }},')
    lines.append("};")
    lines.append("#define MASK_FIXTURE_N (sizeof(MASK_FIXTURES) / sizeof(MASK_FIXTURES[0]))")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
