#!/usr/bin/env python3
"""Convert an image into the firmware's embedded boot-splash header.

Usage:
    python3 scripts/generate_splash.py [input-image] [output-header]

Defaults:
    input  = firmware/assets/splash.png
    output = firmware/src/ui/splash_image.h

Any PIL-readable format works (PNG, JPG, BMP, ...). The image is letterboxed
onto a 320x240 black canvas, converted to RGB565, and RLE-compressed
(uint8 run length + uint16 little-endian color per record, runs crossing row
boundaries freely). draw_splash() in status_bar.c picks the header up via
__has_include — delete the header (and firmware/assets/splash.png) to fall
back to the plain text splash.

To change the boot screen: drop a new image at firmware/assets/splash.png,
re-run this script, rebuild. The header is checked in, so builders without
PIL are unaffected.

A note on size: RLE across flat-color artwork is tiny; photographs and
gradients blow up toward the raw 150 KB. The script refuses anything whose
encoded size exceeds SIZE_LIMIT to keep the app slot comfortable.
"""

import sys
from pathlib import Path

from PIL import Image

W, H = 320, 240
SIZE_LIMIT = 96 * 1024  # bytes of RLE payload


def rgb565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def load_letterboxed(path: Path) -> Image.Image:
    img = Image.open(path).convert("RGB")
    img.thumbnail((W, H), Image.LANCZOS)
    canvas = Image.new("RGB", (W, H), (0, 0, 0))
    canvas.paste(img, ((W - img.width) // 2, (H - img.height) // 2))
    return canvas


def rle_encode(pixels: list[int]) -> bytes:
    out = bytearray()
    i, n = 0, len(pixels)
    while i < n:
        c = pixels[i]
        run = 1
        while i + run < n and run < 255 and pixels[i + run] == c:
            run += 1
        out.append(run)
        out.append(c & 0xFF)
        out.append(c >> 8)
        i += run
    return bytes(out)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "firmware/assets/splash.png"
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else root / "firmware/src/ui/splash_image.h"

    canvas = load_letterboxed(src)
    px = list(canvas.getdata())
    pixels = [rgb565(r, g, b) for (r, g, b) in px]
    payload = rle_encode(pixels)

    if len(payload) > SIZE_LIMIT:
        print(f"ERROR: RLE payload {len(payload)} B exceeds {SIZE_LIMIT} B limit.")
        print("Use flatter artwork (fewer gradients / no photos), or raise the limit")
        print("after checking the app-slot headroom in the map file.")
        return 1

    lines = []
    for i in range(0, len(payload), 16):
        chunk = payload[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    body = "\n".join(lines)

    dst.write_text(f"""/* Auto-generated by scripts/generate_splash.py — DO NOT EDIT.
 * Source image: {src.name} ({len(payload)} B RLE, {len(pixels)} px RGB565).
 * Regenerate: python3 scripts/generate_splash.py
 * Delete this file to fall back to the text splash in draw_splash(). */
#ifndef SPLASH_IMAGE_H
#define SPLASH_IMAGE_H

#include <stdint.h>

#define SPLASH_IMAGE_WIDTH  {W}
#define SPLASH_IMAGE_HEIGHT {H}

/* uint8 run, uint16 LE RGB565 color, repeated; runs cross row boundaries. */
static const uint8_t splash_image_rle[{len(payload)}] = {{
{body}
}};

#endif /* SPLASH_IMAGE_H */
""")
    print(f"{dst}: {len(payload)} B RLE from {src} "
          f"({100.0 * len(payload) / (W * H * 2):.1f}% of raw)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
